### ISSUE TITLE
Tap event trigger twice

### ISSUE THREAD

**Issue by j4587698** [Serg046/EventBinder#66]
Like this demo : https://github.com/j4587698/EventBindingTest

When I tap the border, the event will be printed `tapped` twice.

**Comment by Serg046** [comment]
Have you commited that? I see no any related code lines.

**Comment by oshelton** [comment]
I ran into an issue that sounds similar to this with the Avalonia 11 preview package and I think [the changes in this PR](https://github.com/Serg046/EventBinder/pull/69) should fix it for you as they did for me.

**Comment by Serg046** [comment]
https://www.nuget.org/packages/EventBinder.Avalonia/2.5.1 or
https://www.nuget.org/packages/EventBinder.Avalonia/2.5.1-11.0.0-preview1
should fix the issue, thanks to @oshelton 👍

**Comment by oshelton** [comment]
I don't think it is quite fixed.  Closer, but I'm still encountering this behavior with 2.5.1-11.0.0-preview1.

While before all of my EventBindings to Click events were troublesome; now just some of them are, but the Buttons on which it is still being troublesome is pretty consistent.

I'll try to carve out some time to look into it more tomorrow.

**Comment by Serg046** [comment]
Maybe something related to multithreading/synchronization. I will take a look on this too.

**Comment by oshelton** [comment]
As a workaround, specifying a tiny debounce on the EventBinding appears to make things work better.

Depending on what your handlers are doing though that may not be reasonable.

**Comment by Serg046** [comment]
@oshelton could you please with repro pero? I still have one event fired when I add a handler to a <button/>

**Comment by oshelton** [comment]
It'll be a few days before I can sit down and put one together.  I'll see what I can create.

**Comment by oshelton** [comment]
Sorry it took me so long to get back to this.

I created a simple repro application here:
https://github.com/oshelton/EventBinder_DoubleClickRepro

**Comment by oshelton** [comment]
Clicking the button always seems to run the handler twice.

**Comment by Serg046** [comment]
Thank you @oshelton, should be now fixed

https://www.nuget.org/packages/EventBinder.Avalonia/2.5.2
https://www.nuget.org/packages/EventBinder.Avalonia/2.5.2-11.0.0-preview1

**Comment by oshelton** [comment]
Works great with the repro app.  It's going to take a bit longer to test it in my main app though.  Thanks!
